// <auto-generated />
using System;
using CricketTeam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CricketTeam.Migrations
{
    [DbContext(typeof(CricketTeamContext))]
    [Migration("20201208213754_CricketTeam")]
    partial class CricketTeam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CricketTeam.Model.Events", b =>
                {
                    b.Property<int>("Event_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Fixture_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Fixture_objFixture_Id")
                        .HasColumnType("int");

                    b.Property<string>("ICC_WTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T20_WC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_Id");

                    b.HasIndex("Fixture_objFixture_Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CricketTeam.Model.Fixtures", b =>
                {
                    b.Property<int>("Fixture_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ground_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Player_objPlayer_Id")
                        .HasColumnType("int");

                    b.Property<string>("vs_Team")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Fixture_Id");

                    b.HasIndex("Player_objPlayer_Id");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("CricketTeam.Model.Players", b =>
                {
                    b.Property<int>("Player_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Player_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Player_Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CricketTeam.Model.Ranking", b =>
                {
                    b.Property<int>("Ranking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ODI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player_ID")
                        .HasColumnType("int");

                    b.Property<string>("Player_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player_objPlayer_Id")
                        .HasColumnType("int");

                    b.Property<string>("T20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ranking_Id");

                    b.HasIndex("Player_objPlayer_Id");

                    b.ToTable("Ranking");
                });

            modelBuilder.Entity("CricketTeam.Model.Events", b =>
                {
                    b.HasOne("CricketTeam.Model.Fixtures", "Fixture_obj")
                        .WithMany()
                        .HasForeignKey("Fixture_objFixture_Id");
                });

            modelBuilder.Entity("CricketTeam.Model.Fixtures", b =>
                {
                    b.HasOne("CricketTeam.Model.Players", "Player_obj")
                        .WithMany()
                        .HasForeignKey("Player_objPlayer_Id");
                });

            modelBuilder.Entity("CricketTeam.Model.Ranking", b =>
                {
                    b.HasOne("CricketTeam.Model.Players", "Player_obj")
                        .WithMany()
                        .HasForeignKey("Player_objPlayer_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
